# permissions for end users to view llmmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: llm-operator
    app.kubernetes.io/managed-by: kustomize
  name: llmmodel-viewer-role
rules:
- apiGroups:
  - llm.llm.gitops
  resources:
  - llmmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llm.llm.gitops
  resources:
  - llmmodels/status
  verbs:
  - get
