---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.example.com
  resources:
  - llmdeployments
  - llmmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.example.com
  resources:
  - llmdeployments/finalizers
  - llmmodels/finalizers
  verbs:
  - update
- apiGroups:
  - llm.example.com
  resources:
  - llmdeployments/status
  - llmmodels/status
  verbs:
  - get
  - patch
  - update
