apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-operator
  labels:
    app: llm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-operator
  template:
    metadata:
      labels:
        app: llm-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: llm-operator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "llm-operator"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi